#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/exception/diagnostic_information.hpp>
#include <jde/fwk.h>
#include <jde/fwk/io/protobuf.h>
#include <jde/fwk/chrono.h>
#include <jde/web/usings.h>
#include <jde/web/client/proto/Web.FromServer.pb.h>