syntax = "proto3";
package Jde.App.Proto.FromServer;

import "google/protobuf/timestamp.proto";
import "Common.proto";
import "Web.FromServer.proto";
import "App.proto";
import "Log.proto";

message ClientQuery{
	string query=1;
	string variables=2;
	uint32 executer_pk=3;
	bool raw=4;
}

message ConnectionInfo{
	uint32 app_pk = 1;
	uint32 instance_pk = 2;
	uint32 connection_pk = 3;
	Jde.Web.FromServer.SessionInfo session_info = 4;
	bool auth_result = 5;
	bytes certificate_modulus = 6;
	bytes certificate_exponent = 7;
}


////////////Web/////////////////
message Trace{
	uint64 id=1;
	uint64 instance_id=2;
	google.protobuf.Timestamp time=3;
	Jde.App.Log.Proto.ELogLevel level=4;
	bytes message_id=5;
	bytes file_id=6;
	bytes function_id=7;
	uint32 line=8;
	uint32 user_pk=9;
	repeated string args=10;
}

message Traces{
	uint32 app_id=1;
	repeated Trace values=2;
}

message SubscriptionAck{
	repeated uint32 server_ids = 1;
}

message Message{
	uint32 request_id=1;
	oneof value{
		uint32 ack = 2; //sends on handshake
		Jde.Web.FromServer.SessionInfo session_info = 3;
		string query_result = 4;
		Jde.Proto.Exception exception = 5;
		Traces traces = 6;
		SubscriptionAck subscription_ack = 7;
		string subscription= 8;
		ConnectionInfo connection_info = 9;
		string jwt = 10;
		ClientQuery client_query = 11;

		bytes execute_anonymous = 33; //appServer->2ndServer, no user context.
		Jde.App.Proto.Execute execute = 34; //execute with user context.
		bytes execute_response = 35;
	}
}

message Transmission{
	repeated Message messages = 1;
}