syntax = "proto3";
package Jde.App.Proto.FromClient;

import "google/protobuf/timestamp.proto";
import "Common.proto";
import "App.proto";
import "Log.proto";

message AddSession{
	string domain=1;
	string login_name=2;
	uint32 provider_pk=3;
	string user_endpoint=4;
	bool is_socket = 5;
}

enum ERequestType{
	reserved "UnsubscribeLogs";
	ERequestIdTypeNone = 0;
	Jwt = 1;
}

message Instance{
	string application=1;
	string host=2;
	uint32 pid=3;
	google.protobuf.Timestamp start_time=6;
	uint32 web_port=7;
	string instance_name=8;
	uint32 session_id=9;
	string auth_resource=10;
}
message ForwardExecution{
	uint32 app_pk = 1;
	uint32 app_instance_pk = 2; //0 for any
	bytes execution_transmission = 3;
}

message Unsubscription{
	repeated uint32 request_ids = 1;
}

message Message{
	uint32 request_id=1;
	oneof value{
		AddSession add_session=2; //called from authenticators like OpcGateway
		Jde.Proto.Query query=3;
		Instance instance = 4;
		Jde.App.Log.Proto.LogEntryClient log_entry = 5;
		uint32 session_id = 6; //Attach session id for the socket.
		uint32 session_info = 7; //called from other apps/web page to request information about session TODO graphql
		Jde.Proto.Exception exception = 8;
		ERequestType request_type = 9; //Just the request id is needed.
		Jde.Proto.Query subscription = 10;
		Unsubscription unsubscription = 11;
		bytes jwt = 12; //webPage->appServer to authenticate user.
		string query_result = 13; //appServer query to client results.

		ForwardExecution forward_execution = 31; //webPage->appServer to call execute with creds.
		ForwardExecution forward_execution_anonymous = 32; //call execute with no creds.
		bytes execute_anonymous = 33; //appServer->2ndServer, no user context.
		Jde.App.Proto.Execute execute = 34; //execute with user context.
		bytes execute_response = 35;
	}
}

message Transmission{
	repeated Message messages = 1;
}