#pragma once
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <open62541/client_config_default.h>
#include <open62541/client_highlevel.h>
#include <open62541/client_highlevel_async.h>
#include <open62541/client_subscriptions.h>
#include <open62541/plugin/log_stdout.h>
#include <jde/fwk.h>
#include <jde/fwk/chrono.h>
#include <jde/fwk/str.h>
#include <jde/fwk/co/Task.h>
#include <jde/fwk/io/json.h>
#include <jde/fwk/crypto/OpenSsl.h>
#include <jde/db/meta/AppSchema.h>
#include <jde/db/meta/Table.h>
#include <jde/opc/usings.h>
#include <jde/opc/uatypes/opcHelpers.h>