#pragma once
#include <boost/asio.hpp>
#include <boost/beast.hpp>
#include <boost/asio/strand.hpp>
#include <boost/beast/core.hpp>
#include <boost/beast/http.hpp>
#include <boost/beast/ssl/ssl_stream.hpp>
#include <boost/beast/websocket/stream.hpp>
#include <boost/exception/diagnostic_information.hpp>
#include <boost/lexical_cast.hpp>
#include <boost/unordered/concurrent_flat_map.hpp>
#include <boost/unordered/concurrent_flat_set.hpp>
#include <boost/uuid/uuid.hpp>
#include <boost/uuid/uuid_io.hpp>
#include <open62541/client_config_default.h>
#include <open62541/client_highlevel.h>
#include <open62541/client_highlevel_async.h>
#include <open62541/plugin/log_stdout.h>
#include <open62541/client_subscriptions.h>
#include <jde/fwk.h>
#include <jde/fwk/co/Await.h>
#include <jde/fwk/crypto/OpenSsl.h>
#include <jde/fwk/io/protobuf.h>
#include <jde/access/usings.h>
#include <jde/web/client/proto/Web.FromServer.pb.h>
#include <jde/app/proto/App.FromClient.pb.h>
#include <jde/app/proto/App.FromServer.pb.h>
#include <jde/app/proto/Common.pb.h>
#include <jde/opc/usings.h>
#include <jde/opc/uatypes/NodeId.h>
#include <jde/opc/uatypes/ExNodeId.h>
#include <jde/opc/uatypes/Logger.h>
//the gateway's headers assume its own PCH: its usings (ServerCnnctnNK, MonitorId…), its protos (Jde::Opc::FromServer/FromClient) and its exception type.
#include "../../OpcGateway/src/usings.h"
#include "../../OpcGateway/src/types/UAClientException.h"
DISABLE_WARNINGS
#include <jde/opc/proto/Opc.Common.pb.h>
#include <Opc.FromServer.pb.h>
#include <Opc.FromClient.pb.h>
ENABLE_WARNINGS
